### ISSUE TITLE
Trouble connecting the PowerBI Report

### ISSUE THREAD

**Issue by rvaughan** [RuiRomano/pbigtwmonitor#3]
I've created a new Gen2 storage account and have my PowerBI logs sync'ing to it. However, I'm having some issues connecting the PowerBI template to the storage. Essentially I keep getting the error "This endpoint does not support BlobStorageEvents or SoftDelete." I can't seem to see what I am doing wrong though - I've tried disabling the SoftDelete features on the storage account with no difference.

I can see that the DFS endpoint for my storage account follows a slightly different path, so instead of https://storage.dfs.core.windows.net/pbigatewaymonitor/raw it is https://pbigatewaymonitor.dfs.core.windows.net/raw but when I try that I get "Must be a valid URL" errors.

Do you have any pointers or advice as to how to diagnose the issue further?

**Comment by RuiRomano** [comment]
Please ensure the storage account has "Hierchical Namespace" and you get the dfs endpoint from the endpoint tab in Azure Portal.
